//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaseVehicle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Document
    {
        public int DocId { get; set; }
        [Required]

        public string DocName { get; set; }
        [Required]

        public byte[] DocData { get; set; }
        public string DocContentType { get; set; }
        public Nullable<int> QuoteId { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
