//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaseVehicle.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class VehicleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleDetail()
        {
            this.Quotes = new HashSet<Quote>();
            this.VehicleImages = new HashSet<VehicleImage>();
        }
    
        public int VehicleId { get; set; }
        [Required]

        public string VehicleName { get; set; }
        [Required]

        public string VehicleNo { get; set; }
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
        public int ColorId { get; set; }
        [Required]

        public int Euronum { get; set; }
        [Required]

        public string Kilometers { get; set; }
        [Required]

        public int RegistrationYear { get; set; }
        [Required]

        public double Price { get; set; }
        [Required]

        public int Weight { get; set; }
        [Required]
        [Range(1, 12, ErrorMessage = "Seats Must be between 2 to 12")]

        public int NoOfSeats { get; set; }
        public bool IsSold { get; set; }
        public System.DateTime SoldDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quote> Quotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleImage> VehicleImages { get; set; }
    }
}
