//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaseVehicle.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class VehicleImage
    {
        public int VehicleImgId { get; set; }
        public string VehicleImgName { get; set; }
        public int VehicleId { get; set; }
    
        public virtual VehicleDetail VehicleDetail { get; set; }
        public HttpPostedFileBase[] VehicleImage1 { get; internal set; }
    }
}
